//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ??? 5 2018 13:58:05
//
//      Input file      : 
//      Component name  : baudrate
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module baudrate(Clk, Reset, EN_16x_Baud);
   parameter  C_RATIO = 48;
   input      Clk;
   input      Reset;
   output     EN_16x_Baud;
   reg        EN_16x_Baud;
   
   
   reg [5:0]  count;
   
   
   always @(posedge Clk)
   begin: COUNTER_PROCESS
      
      begin
         if (Reset == 1'b1)
         begin
            count <= 0;
            EN_16x_Baud <= 1'b0;
         end
         else
            if (count == 0)
            begin
               count <= C_RATIO - 1;
               EN_16x_Baud <= 1'b1;
            end
            else
            begin
               count <= count - 1;
               EN_16x_Baud <= 1'b0;
            end
      end
   end
   
endmodule
